# Generated by Django 2.2.6 on 2019-10-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='addres',
            new_name='address',
        ),
    ]
